/**
 * Piped API response shapes, as the real API returns them.
 *
 * The differences from Invidious are the whole reason this fixture exists and
 * are all load-bearing: a video is named by a watch path rather than a bare
 * id, upload time is in milliseconds, the description is HTML, and a format's
 * MIME type and codec arrive in two separate fields. Getting any of those
 * wrong produces a record that looks fine and plays nothing.
 */

export const PIPED_A = "https://piped-a.example.test";
export const PIPED_B = "https://piped-b.example.test";

export const PIPED_CONFIG = {
  privateInstanceUrl: "",
  publicFallbackInstances: [
    { url: PIPED_A, api: "piped" },
    { url: PIPED_B, api: "piped" }
  ]
};

/** A search or trending row. */
export function pipedVideo(id, title, overrides = {}) {
  return {
    url: `/watch?v=${id}`,
    type: "stream",
    title,
    thumbnail: `${PIPED_A}/vi/${id}/hqdefault.jpg`,
    uploaderName: "Example Channel",
    uploaderUrl: "/channel/UCexampleexampleexample",
    uploaderAvatar: `${PIPED_A}/avatar.jpg`,
    uploadedDate: "3 years ago",
    shortDescription: "A description returned by the instance.",
    duration: 213,
    views: 1234567,
    // Piped reports this in milliseconds, unlike Invidious.
    uploaded: 1_600_000_000_000,
    uploaderVerified: true,
    isShort: false,
    ...overrides
  };
}

export function pipedChannel(id = "UCchannelchannelchannel") {
  return {
    url: `/channel/${id}`,
    type: "channel",
    name: "Example Channel",
    thumbnail: `${PIPED_A}/ch.jpg`,
    description: "Channel description.",
    subscribers: 512000,
    videos: 340,
    verified: true
  };
}

export function pipedPlaylist(id = "PLexampleexample") {
  return {
    url: `/playlist?list=${id}`,
    type: "playlist",
    name: "Example Playlist",
    thumbnail: `${PIPED_A}/pl.jpg`,
    uploaderName: "Example Channel",
    videos: 2
  };
}

export function pipedSearch(rows) {
  return { items: rows, nextpage: null, suggestion: null, corrected: false };
}

/**
 * A `/streams` body.
 *
 * Note what is not here: no `videoId`. Piped does not echo the id back, so the
 * id the caller asked for is the only thing that identifies the record.
 */
export function pipedStreams(overrides = {}) {
  const proxy = `${PIPED_A}/videoplayback`;
  return {
    title: "An Example Video",
    description: "Line one.<br>Line two &amp; three.<p>A paragraph.</p>",
    uploadDate: "2020-09-13",
    uploader: "Example Channel",
    uploaderUrl: "/channel/UCexampleexampleexample",
    uploaderAvatar: `${PIPED_A}/avatar.jpg`,
    thumbnailUrl: `${PIPED_A}/vi/dQw4w9WgXcQ/maxres.jpg`,
    hls: null,
    dash: null,
    uploaderVerified: true,
    duration: 213,
    views: 8675309,
    likes: 42000,
    dislikes: -1,
    livestream: false,
    proxyUrl: `${PIPED_A}/proxy`,
    audioStreams: [
      {
        url: `${proxy}?itag=140`,
        format: "M4A",
        quality: "128 kbps",
        mimeType: "audio/mp4",
        codec: "mp4a.40.2",
        videoOnly: false,
        itag: 140,
        bitrate: 128000,
        contentLength: 3456789,
        width: 0,
        height: 0,
        fps: 0
      }
    ],
    videoStreams: [
      {
        url: `${proxy}?itag=22`,
        format: "MPEG_4",
        quality: "720p",
        mimeType: "video/mp4",
        codec: null,
        videoOnly: false,
        itag: 22,
        bitrate: 1500000,
        contentLength: 22345678,
        width: 1280,
        height: 720,
        fps: 25
      },
      {
        url: `${proxy}?itag=18`,
        format: "MPEG_4",
        quality: "360p",
        mimeType: "video/mp4",
        codec: null,
        videoOnly: false,
        itag: 18,
        bitrate: 560000,
        contentLength: 7654321,
        width: 640,
        height: 360,
        fps: 25
      },
      {
        url: `${proxy}?itag=137`,
        format: "MPEG_4",
        quality: "1080p",
        mimeType: "video/mp4",
        codec: "avc1.640028",
        videoOnly: true,
        itag: 137,
        bitrate: 4400000,
        contentLength: 45678901,
        width: 1920,
        height: 1080,
        fps: 25
      }
    ],
    relatedStreams: [pipedVideo("ccccccccccc", "Something else")],
    subtitles: [
      { url: `${PIPED_A}/api/v1/captions/x?lang=en`, mimeType: "text/vtt", name: "English", code: "en", autoGenerated: false }
    ],
    chapters: [],
    previewFrames: []
  };
}

/** A live broadcast: HLS, and no muxed file to fall back to. */
export function pipedLive(id = "liveaaaaaaa") {
  return {
    ...pipedStreams(),
    title: "A Live Broadcast",
    livestream: true,
    duration: 0,
    hls: `${PIPED_A}/api/manifest/hls/${id}.m3u8`,
    videoStreams: [],
    audioStreams: []
  };
}
